module MyterialColors

include("types.jl")
include("codes.jl")
include("utils.jl")
include("palette.jl")

export RGB,Hex
export rgb2hex,hex2rgb
export Palette


export red_lighter,
    red_light,
    red,
    red_dark,
    red_darker,
    pink_lighter,
    pink_light,
    pink,
    pink_dark,
    pink_darker,
    purple_lighter,
    purple_light,
    purple,
    purple_dark,
    purple_darker,
    deep_purple_lighter,
    deep_purple_light,
    deep_purple,
    deep_purple_dark,
    deep_purple_darker,
    indigo_lighter,
    indigo_light,
    indigo,
    indigo_dark,
    indigo_darker,
    blue_lighter,
    blue_light,
    blue,
    blue_dark,
    blue_darker,
    light_blue_lighter,
    light_blue_light,
    light_blue,
    light_blue_dark,
    light_blue_darker,
    cyan_lighter,
    cyan_light,
    cyan,
    cyan_dark,
    cyan_darker,
    teal_lighter,
    teal_light,
    teal,
    teal_dark,
    teal_darker,
    green_lighter,
    green_light,
    green,
    green_dark,
    green_darker,
    light_green_lighter,
    light_green_light,
    light_green,
    light_green_dark,
    light_green_darker,
    lime_lighter,
    lime_light,
    lime,
    lime_dark,
    lime_darker,
    yellow_lighter,
    yellow_light,
    yellow,
    yellow_dark,
    yellow_darker,
    amber_lighter,
    amber_light,
    amber,
    amber_dark,
    amber_darker,
    orange_lighter,
    orange_light,
    orange,
    orange_dark,
    orange_darker,
    salmon_lighter,
    salmon_light,
    salmon,
    salmon_dark,
    salmon_darker,
    brown_lighter,
    brown_light,
    brown,
    brown_dark,
    brown_darker,
    grey_lighter,
    grey_light,
    grey,
    grey_dark,
    grey_darker,
    blue_grey_lighter,
    blue_grey_light,
    blue_grey,
    blue_grey_dark,
    blue_grey_darker,
    black,
    white




end
